version: '3.8'

services:
  trip-service:
    build: ./trip
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://trip-db:5432/tripdb
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888/"
    depends_on:
      - trip-db
      - config-server

  user-service:
    build: ./user
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/userdb
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888/"
    depends_on:
      - user-db
      - config-server

  trip-db:
    image: postgres
    container_name: trip-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tripdb
    volumes:
      - trip_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" 

  user-db:
    image: postgres
    container_name: user-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    volumes:
      - user_data:/var/lib/postgresql/data
    ports:
      - "5434:5432" 

  config-server:
    image: hyness/spring-cloud-config-server
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: "https://github.com/madisonmigliori/sfwe496"
      SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH_PATHS: "semesterproject"
    depends_on:
      - trip-db
      - user-db

volumes:
  trip_data:
    driver: local
  user_data:
    driver: local
