version: '3.8'

services:
  trip-service:
    build: ./trip
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tripdb
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db
      - config-server

  user:
    build: ./user
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/userdb
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db
      - config-server

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres_db
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  config-server:
    image:  hyness/spring-cloud-config-server
    ports:
      - "8888:8888"
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: "https://github.com/madisonmigliori/sfwe496"
      SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH_PATHS: "semesterproject"
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local
