server:
  port: 8072

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: trip-service
          uri: lb://TRIP-SERVICE
          predicates:
            - Path=/trip/**
