spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true 

      routes:

        - id: user-service
          uri: lb://user-service  
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}  


        - id: trip-service
          uri: lb://trip-service  
          predicates:
            - Path=/trips/**  
          filters:
            - name: CircuitBreaker 
              args:
                name: tripServiceCB 
                fallbackUri: forward:/fallback/trips
        - id: fallback-service
          uri: forward:/fallback/trips  
          predicates:
            - Path=/fallback/trips  
            
management:
  endpoints:
    web:
      exposure:
        include: "gateway, health, info"
