server:
  port: 8072

spring:
  application:
    name: gateway-server
  cloud:
    config:
      uri: http://localhost:8071
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<segment>.*), /$\{segment}
        - id: trip-service
          uri: lb://TRIP-SERVICE
          predicates:
            - Path=/trips/**
          filters:
            - name: CircuitBreaker
              args:
                name: tripServiceCB
                fallbackUri: forward:/fallback/trips
        - id: fallback-service
          uri: forward:/fallback/trips
          predicates:
            - Path=/fallback/trips

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
