spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true  # Ensures that service names are in lowercase

      routes:
        # User Service route configuration
        - id: user-service
          uri: lb://user-service  
          predicates:
            - Path=/user/**  # Match requests starting with /user/*
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}  

        # Trip Service route configuration with CircuitBreaker
        - id: trip-service
          uri: lb://trip-service  
          predicates:
            - Path=/trips/**  
          filters:
            - name: CircuitBreaker 
              args:
                name: tripServiceCB 
                fallbackUri: forward:/fallback/trips 

        # Fallback route for trips service
        - id: fallback-service
          uri: forward:/fallback/trips  
          predicates:
            - Path=/fallback/trips  
